
package edu.kalum.workerenrollmentprocess.core.client.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnrollmentServiceImpService", targetNamespace = "http://beans.core.enrollment.kalum.edu/", wsdlLocation = "http://armandohub:8080/EnrollmentServiceImpService/EnrollmentServiceImp?wsdl")
public class EnrollmentServiceImpService
    extends Service
{

    private final static URL ENROLLMENTSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENROLLMENTSERVICEIMPSERVICE_EXCEPTION;
    private final static QName ENROLLMENTSERVICEIMPSERVICE_QNAME = new QName("http://beans.core.enrollment.kalum.edu/", "EnrollmentServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://armandohub:8080/EnrollmentServiceImpService/EnrollmentServiceImp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENROLLMENTSERVICEIMPSERVICE_WSDL_LOCATION = url;
        ENROLLMENTSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public EnrollmentServiceImpService() {
        super(__getWsdlLocation(), ENROLLMENTSERVICEIMPSERVICE_QNAME);
    }

    public EnrollmentServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENROLLMENTSERVICEIMPSERVICE_QNAME, features);
    }

    public EnrollmentServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, ENROLLMENTSERVICEIMPSERVICE_QNAME);
    }

    public EnrollmentServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENROLLMENTSERVICEIMPSERVICE_QNAME, features);
    }

    public EnrollmentServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnrollmentServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEnrollmentServices
     */
    @WebEndpoint(name = "EnrollmentServiceImpPort")
    public IEnrollmentServices getEnrollmentServiceImpPort() {
        return super.getPort(new QName("http://beans.core.enrollment.kalum.edu/", "EnrollmentServiceImpPort"), IEnrollmentServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEnrollmentServices
     */
    @WebEndpoint(name = "EnrollmentServiceImpPort")
    public IEnrollmentServices getEnrollmentServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans.core.enrollment.kalum.edu/", "EnrollmentServiceImpPort"), IEnrollmentServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENROLLMENTSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw ENROLLMENTSERVICEIMPSERVICE_EXCEPTION;
        }
        return ENROLLMENTSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
